version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.ShortCommit}}
    binary: tuiodo

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# Use the new homebrew_casks section instead of deprecated brews
homebrew_casks:
  - name: tuiodo
    repository:
      owner: spmfte
      name: homebrew-tuiodo
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/spmfte/tuiodo"
    description: "A modern terminal task manager with extensive customization"
    license: MIT
    conflicts:
      - formula: tuiodo
    commit_msg_template: "Update {{ .Name }} to {{ .Version }}"
