version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.ShortCommit}}
    binary: tuiodo

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
      - goos: linux
        format: tar.gz
      - goos: darwin
        format: tar.gz

checksum:
  name_template: 'checksums.txt'

# Use homebrew_casks for modern Homebrew integration
homebrew_casks:
  - name: tuiodo
    repository:
      owner: spmfte
      name: homebrew-tuiodo
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/spmfte/tuiodo"
    description: "A modern terminal task manager with extensive customization"
    license: MIT
    commit_msg_template: "Update tuiodo to {{ .Version }}"
